### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by datamusee** [Wimmics/voidmatic#3]
I've tried to install voidmatic on Ubuntu (version?)
When runing "npm run dev", I get the following error 
🚨 Build failed.

@parcel/transformer-css: Unexpected token '.'

  /home6/moissina/.npm/_npx/19555/lib/node_modules/parcel/node_modules/lightningcss/node/composeVisitors.js:67
        return v?.(item.value);
                 ^

  SyntaxError: Unexpected token '.'
      at wrapSafe (internal/modules/cjs/loader.js:915:16)
      at Module._compile (internal/modules/cjs/loader.js:963:27)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
      at Module.load (internal/modules/cjs/loader.js:863:32)
      at NodePackageManager.load
  (/home6/moissina/.npm/_npx/19555/lib/node_modules/parcel/node_modules/@parcel/package-manager/lib/index.js:3375:15)
      at NodePackageManager.requireSync
  (/home6/moissina/.npm/_npx/19555/lib/node_modules/parcel/node_modules/@parcel/package-manager/lib/index.js:3353:21)
      at Module.m.require (/home6/moissina/.npm/_npx/19555/lib/node_modules/parcel/node_modules/@parcel/package-manager/lib/index.js:3366:25)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (/home6/moissina/.npm/_npx/19555/lib/node_modules/parcel/node_modules/lightningcss/node/index.js:26:34)
      at Module._compile (internal/modules/cjs/loader.js:999:30)

and a similar result with
npm run deploy

**Comment by MaillPierre** [comment]
This seems to be a problem with ubuntu when one installs Node using APT. Apt install an old version of Node while Parcel expects a recent one. The problem should be solved if Node is installed without using apt.
I'll close the issue once my tests on a clean ubuntu VM confirm it.

**Comment by MaillPierre** [comment]
clean install of Node 18 works
